# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otFsevqAv3QJlJJAvM6tuV8KMqnfEOYk
"""

s = "Hi there Sam!"

txt = "Hi there Sam!"
print(txt.split())

planet = "Earth"
diameter = 12742

planet= "Earth"
diameter = 12742

print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

import numpy as np

import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

array =np.arange(20,35,2)
print(array)

import numpy as np
array= np.arange(0,9).reshape((3,3))
print(array)

import numpy as np

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = a,b
print(c)

import pandas as pd

data = {'Name':['Jai', 'Princi', 'Gaurav'],
        'Age':[27, 24, 22]}
df = pd.DataFrame(data)
df[['Name', 'Age']]

pd.date_range(start='2023/1/1', end='2023/2/10')

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['index', 'name', 'age']) 
df[['name', 'age']]