# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hFF0G7rFybea8-shszTmFo8lTpJo223
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

df=pd.read_csv("Mall_Customers.csv")
df.head()

df.info()

df.describe()

print(df.columns)
print(df.dtypes)

print("-------Missing Values----------")
print(df.isnull().sum())
print("-------NULL values-------------")
print(df.isna().sum())

df.shape

columns = ['Age', 'Annual Income (k$)','Spending Score (1-100)']

for i in columns:
    plt.figure()
    sns.kdeplot(df[i],shade=True,hue=df['Genre'])
for i in columns:
    plt.figure()
    sns.boxplot(data=df,x='Genre',y=df[i])

columns = ['Age', 'Annual Income (k$)','Spending Score (1-100)']
for i in columns:
    plt.figure()
    sns.distplot(df[i])

sns.pairplot(df.drop(columns='CustomerID'),hue='Genre')

sns.heatmap(df.drop(columns='CustomerID').corr(),annot=True,cmap='coolwarm')

kss=[]
for i in range(1,11):
    kmeans=KMeans(n_clusters=i)
    kmeans.fit(df[['Annual Income (k$)']])
    kss.append(kmeans.inertia_)
plt.plot(range(1,11),kss)

kss2=[]
for i in range(1,11):
    kmeans2=KMeans(n_clusters=i)
    kmeans2.fit(df[['Annual Income (k$)','Spending Score (1-100)']])
    kss2.append(kmeans2.inertia_)
plt.plot(range(1,11),kss2)

clustering2 = KMeans(n_clusters=5)
clustering2.fit(df[['Annual Income (k$)','Spending Score (1-100)']])
df['Spending and Income Cluster'] =clustering2.labels_

plt.figure(figsize=(10,6))
sns.scatterplot(x = 'Annual Income (k$)',y = 'Spending Score (1-100)',hue='Spending and Income Cluster',  
                 palette=['green','orange','brown','dodgerblue','red'], legend='full',data = df  ,s = 60 )
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)') 
plt.title('Spending Score (1-100) vs Annual Income (k$)')
plt.show()